version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: smartgym_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CLAVE_POSTGRES
      - POSTGRES_DB=smartgym_db
      - TZ=America/Caracas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: smartgym_api
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:CLAVE_POSTGRES@db:5432/smartgym_db?client_encoding=utf8
      - SECRET_KEY=CLAVE_SECRETA
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - TZ=America/Caracas
    volumes:
      - .:/app

volumes:
  postgres_data: