from . import categoria_maquina_schema
from . import cliente_schema
from . import control_acceso_schema
from . import disciplina_schema
from . import entrenador_schema
from . import evaluacion_biometrica_schema
from . import maquina_schema
from . import membresia_schema
from . import metodo_pago_schema
from . import pago_membresia_schema
from . import plan_schema
from . import producto_schema
from . import registro_venta_schema
from . import reserva_schema
from . import rol_schema
from . import sesion_clase_schema
from . import ticket_mantenimiento_schema
from . import token_schema
from . import usuario_schema
from . import venta_producto_schema