"""Creacion de las 19 tablas del gimnasio

Revision ID: b85a69c9143f
Revises: 
Create Date: 2026-05-09 11:05:42.127853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85a69c9143f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_maquina',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre_categoria')
    )
    op.create_index(op.f('ix_categoria_maquina_id_categoria'), 'categoria_maquina', ['id_categoria'], unique=False)
    op.create_table('disciplina',
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.Column('nombre_disc', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_disciplina')
    )
    op.create_index(op.f('ix_disciplina_id_disciplina'), 'disciplina', ['id_disciplina'], unique=False)
    op.create_table('metodo_pago',
    sa.Column('id_metodo', sa.Integer(), nullable=False),
    sa.Column('nombre_metodo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_metodo'),
    sa.UniqueConstraint('nombre_metodo')
    )
    op.create_index(op.f('ix_metodo_pago_id_metodo'), 'metodo_pago', ['id_metodo'], unique=False)
    op.create_table('plan_subscripcion',
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('nombre_plan', sa.String(length=100), nullable=False),
    sa.Column('precio_sub', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_plan'),
    sa.UniqueConstraint('nombre_plan')
    )
    op.create_index(op.f('ix_plan_subscripcion_id_plan'), 'plan_subscripcion', ['id_plan'], unique=False)
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_prod', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_producto_id_producto'), 'producto', ['id_producto'], unique=False)
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_index(op.f('ix_rol_id_rol'), 'rol', ['id_rol'], unique=False)
    op.create_table('maquina',
    sa.Column('id_maquina', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('estado_maquina', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_maquina.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_maquina')
    )
    op.create_index(op.f('ix_maquina_id_maquina'), 'maquina', ['id_maquina'], unique=False)
    op.create_table('usuario',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('estatus_usuario', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id_user'), 'usuario', ['id_user'], unique=False)
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_cli', sa.String(length=100), nullable=False),
    sa.Column('apellido_cli', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_user'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cedula')
    )
    op.create_index(op.f('ix_cliente_id_cliente'), 'cliente', ['id_cliente'], unique=False)
    op.create_table('entrenador',
    sa.Column('id_entrenador', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_ent', sa.String(length=100), nullable=False),
    sa.Column('apellido_ent', sa.String(length=100), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_user'], ),
    sa.PrimaryKeyConstraint('id_entrenador')
    )
    op.create_index(op.f('ix_entrenador_id_entrenador'), 'entrenador', ['id_entrenador'], unique=False)
    op.create_table('ticket_mantenimiento',
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_maquina', sa.Integer(), nullable=False),
    sa.Column('desc_fallo', sa.Text(), nullable=False),
    sa.Column('costo_reparacion', sa.Float(), nullable=True),
    sa.Column('fecha_falla', sa.DateTime(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_maquina'], ['maquina.id_maquina'], ),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    op.create_index(op.f('ix_ticket_mantenimiento_id_ticket'), 'ticket_mantenimiento', ['id_ticket'], unique=False)
    op.create_table('control_acceso',
    sa.Column('id_acceso', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha_entrada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_acceso')
    )
    op.create_index(op.f('ix_control_acceso_id_acceso'), 'control_acceso', ['id_acceso'], unique=False)
    op.create_table('evaluacion_biometrica',
    sa.Column('id_evaluacion', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_entrenador', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('porc_grasa', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('historial', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_entrenador'], ['entrenador.id_entrenador'], ),
    sa.PrimaryKeyConstraint('id_evaluacion')
    )
    op.create_index(op.f('ix_evaluacion_biometrica_id_evaluacion'), 'evaluacion_biometrica', ['id_evaluacion'], unique=False)
    op.create_table('pago_membresia',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_metodo', sa.Integer(), nullable=False),
    sa.Column('monto_membresia', sa.Float(), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('estado_pago', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_metodo'], ['metodo_pago.id_metodo'], ),
    sa.PrimaryKeyConstraint('id_pago'),
    sa.UniqueConstraint('referencia')
    )
    op.create_index(op.f('ix_pago_membresia_id_pago'), 'pago_membresia', ['id_pago'], unique=False)
    op.create_table('sesion_clase',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.Column('id_entrenador', sa.Integer(), nullable=False),
    sa.Column('fecha_inic', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('cupos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplina.id_disciplina'], ),
    sa.ForeignKeyConstraint(['id_entrenador'], ['entrenador.id_entrenador'], ),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_index(op.f('ix_sesion_clase_id_sesion'), 'sesion_clase', ['id_sesion'], unique=False)
    op.create_table('venta_producto',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_metodo', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('estado_venta', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_metodo'], ['metodo_pago.id_metodo'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_index(op.f('ix_venta_producto_id_venta'), 'venta_producto', ['id_venta'], unique=False)
    op.create_table('membresia',
    sa.Column('id_membresia', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_pago'], ['pago_membresia.id_pago'], ),
    sa.ForeignKeyConstraint(['id_plan'], ['plan_subscripcion.id_plan'], ),
    sa.PrimaryKeyConstraint('id_membresia')
    )
    op.create_index(op.f('ix_membresia_id_membresia'), 'membresia', ['id_membresia'], unique=False)
    op.create_table('registro_venta',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta_producto.id_venta'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    op.create_index(op.f('ix_registro_venta_id_registro'), 'registro_venta', ['id_registro'], unique=False)
    op.create_table('reserva',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesion_clase.id_sesion'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_index(op.f('ix_reserva_id_reserva'), 'reserva', ['id_reserva'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserva_id_reserva'), table_name='reserva')
    op.drop_table('reserva')
    op.drop_index(op.f('ix_registro_venta_id_registro'), table_name='registro_venta')
    op.drop_table('registro_venta')
    op.drop_index(op.f('ix_membresia_id_membresia'), table_name='membresia')
    op.drop_table('membresia')
    op.drop_index(op.f('ix_venta_producto_id_venta'), table_name='venta_producto')
    op.drop_table('venta_producto')
    op.drop_index(op.f('ix_sesion_clase_id_sesion'), table_name='sesion_clase')
    op.drop_table('sesion_clase')
    op.drop_index(op.f('ix_pago_membresia_id_pago'), table_name='pago_membresia')
    op.drop_table('pago_membresia')
    op.drop_index(op.f('ix_evaluacion_biometrica_id_evaluacion'), table_name='evaluacion_biometrica')
    op.drop_table('evaluacion_biometrica')
    op.drop_index(op.f('ix_control_acceso_id_acceso'), table_name='control_acceso')
    op.drop_table('control_acceso')
    op.drop_index(op.f('ix_ticket_mantenimiento_id_ticket'), table_name='ticket_mantenimiento')
    op.drop_table('ticket_mantenimiento')
    op.drop_index(op.f('ix_entrenador_id_entrenador'), table_name='entrenador')
    op.drop_table('entrenador')
    op.drop_index(op.f('ix_cliente_id_cliente'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_usuario_id_user'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_maquina_id_maquina'), table_name='maquina')
    op.drop_table('maquina')
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_producto_id_producto'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_plan_subscripcion_id_plan'), table_name='plan_subscripcion')
    op.drop_table('plan_subscripcion')
    op.drop_index(op.f('ix_metodo_pago_id_metodo'), table_name='metodo_pago')
    op.drop_table('metodo_pago')
    op.drop_index(op.f('ix_disciplina_id_disciplina'), table_name='disciplina')
    op.drop_table('disciplina')
    op.drop_index(op.f('ix_categoria_maquina_id_categoria'), table_name='categoria_maquina')
    op.drop_table('categoria_maquina')
    # ### end Alembic commands ###
